### ISSUE TITLE
docker-compose file missing

### ISSUE THREAD

**Issue by patlachance** [mendix/azure-docker-mendix#13]
Hi, the "test" directory seems to be excluded and the docker-compose file is missing.

**Comment by RaphaelAudet** [comment]
Correct, the docker-compose tests have been removed from this projects (config and docker-compose is to far from the actually setup to use).

I'd recommend building a new docker-compose file for your setup (like https://github.com/RaphaelAudet/mendix-docker-compose).

I'll fix the docs, thanks for the issue.
